/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#0c0f0f",
        "on-primary-container": "#525151",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#ffffff",
        "outline-variant": "#adb3b4",
        "surface-bright": "#f9f9f9",
        "error-container": "#fe8983",
        "secondary-fixed-dim": "#d5d4d4",
        "on-secondary": "#faf8f8",
        "surface-container-high": "#e4e9ea",
        "error": "#9f403d",
        "on-secondary-fixed-variant": "#5b5b5b",
        "inverse-primary": "#ffffff",
        "on-tertiary": "#faf8ff",
        "primary-container": "#e5e2e1",
        "primary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#f9f7ff",
        "tertiary-container": "#3e76fe",
        "surface-container-low": "#f2f4f4",
        "surface-container-highest": "#dde4e5",
        "tertiary-fixed-dim": "#2d68f0",
        "secondary-container": "#e3e2e2",
        "on-primary": "#faf7f6",
        "tertiary": "#0053dc",
        "on-error-container": "#752121",
        "on-primary-fixed-variant": "#5c5b5b",
        "primary-fixed-dim": "#d6d4d3",
        "tertiary-fixed": "#3e76fe",
        "on-error": "#fff7f6",
        "surface-container": "#ebeeef",
        "on-surface": "#2d3435",
        "inverse-on-surface": "#9c9d9d",
        "on-secondary-fixed": "#3f3f3f",
        "secondary-dim": "#535353",
        "on-secondary-container": "#515252",
        "secondary": "#5f5f5f",
        "outline": "#757c7d",
        "primary-dim": "#535252",
        "error-dim": "#4e0309",
        "primary": "#5f5e5e",
        "surface": "#f9f9f9",
        "background": "#f9f9f9",
        "on-primary-fixed": "#403f3f",
        "on-background": "#2d3435",
        "surface-variant": "#dde4e5",
        "surface-tint": "#5f5e5e",
        "surface-dim": "#d4dbdd",
        "on-tertiary-container": "#000000",
        "tertiary-dim": "#0049c2",
        "on-surface-variant": "#5a6061",
        "secondary-fixed": "#e3e2e2",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        md: "0.375rem",
      },
    },
  },
  plugins: [],
};
